---
# tasks file for jenkins role

- name: Ensure apt package index is updated
  apt:
    update_cache: true

- name: Ensure OpenJDK 17 is installed
  apt:
    name: openjdk-17-jre
    state: present

- name: Ensure jenkins.io apt key is present
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Ensure jenkins repository is configured
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    update_cache: true
    state: present

- name: Ensure jenkins package is installed
  apt:
    name: jenkins
    state: present

- name: Ensure jenkins service is enabled and started
  service:
    name: jenkins
    enabled: true
    state: started

- name: Wait for Jenkins port 8080 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 8080
    delay: 10

- name: Get Jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: result

- name: Print Jenkins initial admin password
  debug:
    msg: "Jenkins is available at (http://{{ inventory_hostname }}:8080/). Initial Admin Password: {{ result.stdout }}"

- name: Ensure user jenkins is added to docker group
  user:
    name: "jenkins"
    groups: "docker"
    append: true

- name: Ensure passwordless sudo is configured for user jenkins to use kubectl
  shell: echo 'jenkins ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/jenkins

- name: Ensure the instance is rebooted
  ansible.builtin.reboot:
